language: php
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

before_script:
  - git fetch --unshallow --tags
  - composer install --prefer-source
  - composer global require 'kherge/box=~2.4' --prefer-source
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - php vendor/atoum/atoum/scripts/coverage.php --format xml --output clover.xml
  - composer install --no-dev --optimize-autoloader
  - ~/.composer/vendor/bin/box build
  - composer install
  - PICKLE_BEHAT_PROCESS_TIMEOUT=0 vendor/bin/behat --format=progress

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

deploy:
  provider: releases
  api_key:
    secure: S5zmtkDizyJpPIVpJeTuLpLC4/AM5SILXR37wbdIo5GY2yWIdDDZqZ19J5cy0SmqSuYjdYjg8XHQtv0CsZv8gxQX120o/ODwzAtUlPb0PyTvIU2fKaHw8Dcj4ZP/NC9DIItwUYP1JfxubP1sKWPl/GUiZr4HB2ufhUEShWbX0q0=
  file: pickle.phar
  skip_cleanup: true
  on:
    tags: true
    repo: FriendsOfPHP/pickle
